# This workflow runs on every push and checks whether everything looks good

name: Quick check

on:
  push:
    tags-ignore:
      - v*
    branches:
      - "*"

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quick_check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Cargo fmt
        run: cargo fmt --all -- --check

  quick_check-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cargo clippy
        run: cargo clippy --all-features -- -D warnings

  quick_check-tests:
    strategy:
      fail-fast: false
      matrix:
        feature-flags:
          - ''
          - '--all-features'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@stable

      - name: Cargo test
        run: cargo test ${{ matrix.feature-flags }}

      - name: Cargo check
        run: cargo check ${{ matrix.feature-flags }}

  quick_check-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Cache Nix dependencies
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - uses: actions/checkout@v6

      - name: Check flake
        run: nix flake check

      - name: Build flake
        run: nix build

      - name: Test run flake
        run: nix run . -- --version
